Vagrant.configure("2") do |config|

  config.vm.define "proxy" do |proxy|
    proxy.vm.box = "generic/rocky9"
    proxy.vm.hostname = "proxy"
    proxy.vm.network "private_network", ip: "192.168.56.10"
    proxy.vm.provision "file", source: "haproxy.cfg", destination: "/tmp/haproxy.cfg"
    proxy.vm.provision "shell", path: "provision_proxy.sh"
  end

  config.vm.define "backend1" do |backend1|
    backend1.vm.box = "generic/rocky9"
    backend1.vm.hostname = "backend1"
    backend1.vm.network "private_network", ip: "192.168.56.11"
    backend1.vm.provision "file", source: "sito1.html", destination: "/tmp/sito1.html"
    backend1.vm.provision "shell", path: "provision_backend.sh", args: "sito1"
  end

  config.vm.define "backend2" do |backend2|
    backend2.vm.box = "generic/rocky9"
    backend2.vm.hostname = "backend2"
    backend2.vm.network "private_network", ip: "192.168.56.12"
    backend2.vm.provision "file", source: "sito2.html", destination: "/tmp/sito2.html"
    backend2.vm.provision "shell", path: "provision_backend.sh", args: "sito2"
  end

end
