Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end
  install_docker = <<-SHELL
    curl -fsSL https://get.docker.com | sh
    usermod -aG docker vagrant
    docker pull ealen/echo-server
    SHELL

  config.vm.define "node1" do |node1|
      node1.vm.hostname = "node1"
      node1.vm.network "private_network", ip:"192.168.56.11"
      node1.vm.provision "shell", inline: install_docker
  end

  config.vm.define "node2" do |node2|
    node2.vm.hostname = "node2"
    node2.vm.network "private_network", ip:"192.168.56.12"
    node2.vm.provision "shell", inline: install_docker
  end
end
